name: main
on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Clone Suitsparse
      run: git clone --depth 1 --branch stable https://github.com/DrTimothyAldenDavis/SuiteSparse suitesparse
    - name: Clone Pybind
      run: | 
        git clone --depth 1 --branch stable https://github.com/pybind/pybind11 pybind11


    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: pypa/cibuildwheel@v2.13.0
      env:
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_PRERELEASE_PYTHONS: true

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl